name: Deploy Project
on: [push, workflow_dispatch]
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
    - name: download code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: run tests
      run: npm run test
    - name: build the code
      run: npm run build
    - name: deploy
      run: echo "deployed succesfully"
