<<<<<<< HEAD
name: Deploy Project2
=======
name: Deploy Project2 lint test deploy
>>>>>>> b1a4bf91877120e4461074fca5fd1e2bd7f9ed79
on: [push, workflow_dispatch]
jobs: 
  lint: 
    runs-on: ubuntu-latest
    steps: 
    - name: download code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Lint
  test: 
    runs-on: ubuntu-latest
    steps: 
    - name: download code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: test
      run: npm run test
  deploy: 
    runs-on: ubuntu-latest
    steps: 
    - name: download code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: build
      run: npm run build
    - name: deploy
      run: echo "application deployed succesfully"
